[tool.poetry]
name = "risc-v-python"
version = "0.1.0"
description = "RISC-V implementation in Python"
authors = ["Arnor Nolen <andrey1gorbulin@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "risc_v_python"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.23.4"
pyelftools = "^0.29"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
